--- a/curses/vt/Makefile	2026-05-16 16:52:34.304215536 -0400
+++ b/curses/vt/Makefile	2026-05-16 17:07:02.544209834 -0400
@@ -19,11 +19,11 @@
 
 RM		= rm -f
 
-CFLAGS  = -Wall -Wextra -pedantic -Werror
+CFLAGS  += -Wall -Wextra -pedantic
 ifeq ($(DEBUG),Y)
 	CFLAGS  += -g -DPDCDEBUG
 else
-	CFLAGS  += -O2
+	CFLAGS  += -O2 -DVT -DPDC_VT=RGB -DPDC_RGB -fomit-frame-pointer
 endif
 
 ifeq ($(DOS),Y)
@@ -49,20 +49,25 @@
 endif
 
 ifdef _w64
-	PREFIX  = x86_64-w64-mingw32-
+	PREFIX = x86_64-w64-mingw32-
 	IS_WIN = Y
 endif
 
 ifdef _w32
-	PREFIX  = i686-w64-mingw32-
+	PREFIX = i686-w64-mingw32-
 	IS_WIN = Y
 endif
 
 ifdef _a64
-	PREFIX  = aarch64-w64-mingw32-
+	PREFIX = aarch64-w64-mingw32-
 	IS_WIN = Y
 endif
 
+ifdef _a32
+      PREFIX = armv7-w64-mingw32-
+      IS_WIN = Y
+endif
+
 ifeq ($(OS),Windows_NT)
 	IS_WIN = Y
 	RM = cmd /c del
@@ -72,7 +77,7 @@
 	E = .exe
 endif
 
-LIBNAME=libpdcurses
+LIBNAME=pdcurses
 DLLNAME=pdcurses
 
 LIBFLAGS = rv
